name: celepraty
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^1.0.3
  flutter_screenutil: ^5.1.1
  adobe_xd: ^2.0.1
  cached_video_player: ^2.0.3
  auto_size_text: ^3.0.0
  cupertino_icons: ^1.0.2
  simple_animations: ^1.3.3
  dots_indicator: ^2.0.0
  image_picker: ^0.8.5
  flutter_credit_card: ^3.0.1
  checkbox_grouped:  ^1.7.1
  curved_navigation_bar: ^1.0.3
  dropdown_below: ^1.0.3
  flutter_windowmanager: ^0.2.0
  flutter_flushbar: ^0.0.2
  alert_dialog: ^1.0.1
  card_swiper: ^2.0.1
  path_provider: ^2.0.10
  url_launcher: ^6.0.20
  simple_gradient_text: ^1.2.2
  video_player: ^2.4.7
  smooth_page_indicator: ^1.0.0+2
  http:
  flutter_share: ^2.0.0
  shared_preferences: ^2.0.13
  cached_network_image: ^3.2.0
  flutter_lints: ^1.0.0
  open_file: ^3.2.1
  email_validator:
  lottie: ^1.2.2
  country_code_picker: ^2.0.2
  file_picker: ^4.5.1
  share_plus: ^4.0.6
  pdf: ^3.8.4
  printing: ^5.9.1
  shimmer: ^2.0.0
  gallery_saver:
  dropdown_button2:
  flutter_facebook_auth: ^4.4.1
  google_sign_in: ^5.0.3
  dio: ^4.0.6
  google_fonts: ^3.0.1
  audio_video_progress_bar: ^0.10.0
  another_audio_recorder: ^1.0.1
  permission_handler: ^10.0.0
  intl:
  just_audio_libwinmedia:
  just_audio: ^0.9.30
  audioplayers:
  flutter_sound:
  rxdart:
  http_parser:
  external_path:
  firebase_messaging: ^11.2.4
  firebase_analytics: any
  flutter_local_notifications: ^9.9.1
  firebase_core:
  badges:
  camera: ^0.10.0+3
  video_compress: ^3.1.0
  hand_signature: ^2.3.0+1
  flutter_pw_validator: ^1.4.2
  flutter_paytabs_bridge: ^2.3.0
  animations: ^2.0.1
  simple_circular_progress_bar: ^1.0.2
  liquid_progress_indicator: ^0.4.0
  image_gallery_saver: ^1.7.1
dev_dependencies:
  flutter_launcher_icons: ^0.9.2

flutter_icons:
  android: true
  ios: true
  image_path_android: "@mipmap/ic_launcher"
  image_path_ios: "@mipmap/ic_launcher"


  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/font/
    - assets/image/
    - assets/Svg/
    - assets/lottie/
    - assets/video/don.mp4

  # Fonts:
  fonts:
    - family: Cairo
      fonts:
        - asset: assets/font/Cairo-Regular.ttf
          style: italic

    - family: Circular Std
      fonts:
        - asset: assets/font/Circular Std Font.otf

    - family: DINNextLTArabic
      fonts:
        - asset: assets/font/DINNextLTArabic-Regular-2.ttf

